# Generated by Django 3.2.5 on 2021-07-02 10:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
