# Generated by Django 3.2.5 on 2021-07-02 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='active',
        ),
    ]
